name: Docker push

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Docker build
        run: sh env/build.sh

      - name: Docker push
        run: docker push tmvdl/dart -a
